<?php

	include "antropometria_est.php";
	include "bitacora.php";
	include "carnet_patria.php";
	include "condiciones_est.php";
	include "contactos_aux.php";
	include "datos_academicos.php";
	include "datos_economicos.php";
	include "datos_laborales.php";
	include "datos_salud.php";
	include "datos_sociales.php";
	include "datos_vivienda.php";
	include "direcciones.php";
	include "estudiantes.php";
	include "grado_a_cursar_est.php";
	include "inscripciones.php";
	include "mantenimiento.php";
	include "observaciones_est.php";
	include "padres.php";
	include "per_academico.php";
	include "personas.php";
	include "representantes.php";
	include "tallas_est.php";
	include "telefonos.php";
	include "usuarios.php";
	include "vac_covid19_est.php";
	include "vacunas_est.php";


	include "../logs/error_handler.php";
	include "../controladores/conexion.php";

	// $personas = new personas();
	// $telefonos = new telefonos();
	// $carnet_patria = new carnet_patria();
	// $datos_laborales = new datos_laborales();
	// $datos_vivienda = new datos_vivienda();
	// $direcciones = new direcciones();
	// $representantes = new representantes();
	// $contactos_aux = new contactos_aux();
	// $datos_economicos = new datos_economicos();
	// $padres = new padres();
	// $estudiantes = new estudiantes();
	// $antropometria_est = new antropometria_est();
	// $condiciones_est = new condiciones_est();
	// $datos_salud = new datos_salud();
	// $datos_sociales = new datos_sociales();
	// $datos_academicos = new datos_academicos();
	// $grado_a_cursar_est = new grado_a_cursar_est();
	// $observaciones_est = new observaciones_est();
	// $tallas_est = new tallas_est();
	// $vac_covid19_est = new vac_covid19_est();
	// $vacunas_est = new vacunas_est();
	// $inscripciones = new inscripciones();
	// $per_academico = new per_academico();
	// $usuarios = new usuarios();
	// $bitacora = new bitacora();

	// $lista_estudiantes = $estudiantes->mostrar_estudiantes();
	// $lista_padres = $padres->mostrar_padres();
	// $lista_representantes = $representantes->mostrar_representantes();
	// $lista_usuarios = $usuarios->mostrar_usuarios();

	// $vac_covid19_est->set_vac_aplicada("VERO CELL");
	// foreach ($lista_estudiantes as $dato) {
	// 	$personas->set_cedula($dato["cedula"]);
	// 	$personas->set_p_nombre($dato["p_nombre"]);
	// 	$personas->set_s_nombre($dato["s_nombre"]);
	// 	$personas->set_p_apellido($dato["p_apellido"]);
	// 	$personas->set_s_apellido($dato["s_apellido"]);
	// 	$personas->set_fecha_nacimiento($dato["fecha_nacimiento"]);
	// 	$personas->set_lugar_nacimiento($dato["lugar_nacimiento"]);
	// 	$personas->set_genero($dato["genero"]);
	// 	$personas->set_email($dato["email"]);
	// 	$direcciones->set_estado($dato["estado"]);
	// 	$direcciones->set_municipio($dato["municipio"]);
	// 	$direcciones->set_parroquia($dato["parroquia"]);
	// 	$direcciones->set_sector($dato["sector"]);
	// 	$direcciones->set_calle($dato["calle"]);
	// 	$direcciones->set_nro_casa($dato["nro_casa"]);
	// 	$direcciones->set_punto_referencia($dato["punto_referencia"]);
	// 	$carnet_patria->set_codigo_carnet($dato["codigo_carnet"]);
	// 	$carnet_patria->set_serial_carnet($dato["serial_carnet"]);
	// 	$estudiantes->set_estado($dato["estado_inscripcion"]);
	// 	$estudiantes->set_plantel_proced($dato["plantel_proced"]);
	// 	$estudiantes->set_con_quien_vive($dato["con_quien_vive"]);
	// 	$estudiantes->set_relacion_representante($dato["relacion_representante"]);
	// 	$estudiantes->set_cedula_padre($dato["cedula_padre"]);
	// 	$estudiantes->set_cedula_madre($dato["cedula_madre"]);
	// 	$estudiantes->set_cedula_representante($dato["cedula_representante"]);
	// 	$datos_salud->set_lateralidad($dato["lateralidad"]);
	// 	$datos_salud->set_tipo_sangre($dato["tipo_sangre"]);
	// 	$datos_salud->set_medicacion($dato["medicacion"]);
	// 	$datos_salud->set_dieta_especial($dato["dieta_especial"]);
	// 	$datos_salud->set_padecimiento($dato["padecimiento"]);
	// 	$datos_salud->set_impedimento_fisico($dato["impedimento_fisico"]);
	// 	$datos_salud->set_necesidad_educativa($dato["necesidad_educativa"]);
	// 	$datos_salud->set_condicion_vista($dato["condicion_vista"]);
	// 	$datos_salud->set_condicion_dental($dato["condicion_dental"]);
	// 	$datos_salud->set_institucion_medica($dato["institucion_medica"]);
	// 	$datos_salud->set_carnet_discapacidad($dato["carnet_discapacidad"]);
	// 	$vac_covid19_est->set_vac_aplicada($dato["vac_aplicada"]);
	// 	$vac_covid19_est->set_dosis($dato["dosis"]);
	// 	$vac_covid19_est->set_lote($dato["lote"]);
	// 	$tallas_est->set_camisa($dato["camisa"]);
	// 	$tallas_est->set_pantalon($dato["pantalon"]);
	// 	$tallas_est->set_calzado($dato["calzado"]);
	// 	$antropometria_est->set_estatura($dato["estatura"]);
	// 	$antropometria_est->set_peso($dato["peso"]);
	// 	$antropometria_est->set_indice_m_c($dato["indice_m_c"]);
	// 	$antropometria_est->set_circ_braquial($dato["circ_braquial"]);
	// 	$condiciones_est->set_visual($dato["visual"]);
	// 	$condiciones_est->set_motora($dato["motora"]);
	// 	$condiciones_est->set_auditiva($dato["auditiva"]);
	// 	$condiciones_est->set_escritura($dato["escritura"]);
	// 	$condiciones_est->set_lectura($dato["lectura"]);
	// 	$condiciones_est->set_lenguaje($dato["lenguaje"]);
	// 	$condiciones_est->set_embarazo($dato["embarazo"]);
	// 	$observaciones_est->set_social($dato["social"]);
	// 	$observaciones_est->set_fisico($dato["fisico"]);
	// 	$observaciones_est->set_personal($dato["personal"]);
	// 	$observaciones_est->set_familiar($dato["familiar"]);
	// 	$observaciones_est->set_academico($dato["academico"]);
	// 	$observaciones_est->set_otra($dato["otra"]);
	// 	$datos_academicos->set_a_repetido($dato["grado_repetido"]);
	// 	$datos_academicos->set_materias_repetidas($dato["materias_repetidas"]);
	// 	$datos_academicos->set_materias_pendientes($dato["materias_pendientes"]);
	// 	$datos_sociales->set_tiene_canaima($dato["tiene_canaima"]);
	// 	$datos_sociales->set_condicion_canaima($dato["condicion_canaima"]);
	// 	$datos_sociales->set_acceso_internet($dato["acceso_internet"]);
	// 	$grado_a_cursar_est->set_grado_a_cursar($dato["grado_a_cursar"]);
	// 	$grado_a_cursar_est->set_seccion($dato["seccion"]);
	// 	$grado_a_cursar_est->set_id_per_academico($dato["id_per_academico"]);
	// }

	// foreach ($lista_padres as $dato) {
	// 	$personas->set_cedula($dato["cedula"]);
	// 	$personas->set_p_nombre($dato["p_nombre"]);
	// 	$personas->set_s_nombre($dato["s_nombre"]);
	// 	$personas->set_p_apellido($dato["p_apellido"]);
	// 	$personas->set_s_apellido($dato["s_apellido"]);
	// 	$personas->set_fecha_nacimiento($dato["fecha_nacimiento"]);
	// 	$personas->set_lugar_nacimiento($dato["lugar_nacimiento"]);
	// 	$personas->set_genero($dato["genero"]);
	// 	$personas->set_estado_civil($dato["estado_civil"]);
	// 	$personas->set_email($dato["email"]);
	// 	$personas->set_grado_academico($dato["grado_academico"]);
	// 	$direcciones->set_estado($dato["estado"]);
	// 	$direcciones->set_municipio($dato["municipio"]);
	// 	$direcciones->set_parroquia($dato["parroquia"]);
	// 	$direcciones->set_sector($dato["sector"]);
	// 	$direcciones->set_calle($dato["calle"]);
	// 	$direcciones->set_nro_casa($dato["nro_casa"]);
	// 	$direcciones->set_punto_referencia($dato["punto_referencia"]);
	// 	$datos_laborales->set_empleo($dato["empleo"]);
	// 	$datos_laborales->set_lugar_trabajo($dato["lugar_trabajo"]);
	// 	$datos_laborales->set_remuneracion($dato["remuneracion"]);
	// 	$datos_laborales->set_tipo_remuneracion($dato["tipo_remuneracion"]);
	// 	$datos_vivienda->set_condicion($dato["condicion"]);
	// 	$datos_vivienda->set_tipo($dato["tipo"]);
	// 	$datos_vivienda->set_tenencia($dato["tenencia"]);
	// 	$padres->set_pais_residencia($dato["pais_residencia"]);
	// }

	// foreach ($lista_representantes as $dato) {
	// 	$personas->set_cedula($dato["cedula"]);
	// 	$personas->set_p_nombre($dato["p_nombre"]);
	// 	$personas->set_s_nombre($dato["s_nombre"]);
	// 	$personas->set_p_apellido($dato["p_apellido"]);
	// 	$personas->set_s_apellido($dato["s_apellido"]);
	// 	$personas->set_fecha_nacimiento($dato["fecha_nacimiento"]);
	// 	$personas->set_lugar_nacimiento($dato["lugar_nacimiento"]);
	// 	$personas->set_genero($dato["genero"]);
	// 	$personas->set_estado_civil($dato["estado_civil"]);
	// 	$personas->set_email($dato["email"]);
	// 	$personas->set_grado_academico($dato["grado_academico"]);
	// 	$direcciones->set_estado($dato["estado"]);
	// 	$direcciones->set_municipio($dato["municipio"]);
	// 	$direcciones->set_parroquia($dato["parroquia"]);
	// 	$direcciones->set_sector($dato["sector"]);
	// 	$direcciones->set_calle($dato["calle"]);
	// 	$direcciones->set_nro_casa($dato["nro_casa"]);
	// 	$direcciones->set_punto_referencia($dato["punto_referencia"]);
	// 	$carnet_patria->set_codigo_carnet($dato["codigo_carnet"]);
	// 	$carnet_patria->set_serial_carnet($dato["serial_carnet"]);
	// 	$datos_laborales->set_empleo($dato["empleo"]);
	// 	$datos_laborales->set_lugar_trabajo($dato["lugar_trabajo"]);
	// 	$datos_laborales->set_remuneracion($dato["remuneracion"]);
	// 	$datos_laborales->set_tipo_remuneracion($dato["tipo_remuneracion"]);
	// 	$datos_vivienda->set_condicion($dato["condicion"]);
	// 	$datos_vivienda->set_tipo($dato["tipo"]);
	// 	$datos_vivienda->set_tenencia($dato["tenencia"]);
	// 	$datos_economicos->set_banco($dato["banco"]);
	// 	$datos_economicos->set_tipo_cuenta($dato["tipo_cuenta"]);
	// 	$datos_economicos->set_nro_cuenta($dato["nro_cuenta"]);
	// 	$contactos_aux->set_nombre($dato["nombre_aux"]);
	// 	$contactos_aux->set_apellido($dato["apellido_aux"]);
	// 	$contactos_aux->set_prefijo_telefono($dato["pref_aux"]);
	// 	$contactos_aux->set_nro_telefono($dato["numero_aux"]);
	// 	$contactos_aux->set_relacion($dato["relacion_aux"]);
	// }

	// foreach ($lista_usuarios as $dato) {
	// 	$personas->set_cedula($dato["cedula"]);
	// 	$personas->set_p_nombre($dato["p_nombre"]);
	// 	$personas->set_s_nombre($dato["s_nombre"]);
	// 	$personas->set_p_apellido($dato["p_apellido"]);
	// 	$personas->set_s_apellido($dato["s_apellido"]);
	// 	$personas->set_fecha_nacimiento($dato["fecha_nacimiento"]);
	// 	$personas->set_lugar_nacimiento($dato["lugar_nacimiento"]);
	// 	$personas->set_genero($dato["genero"]);
	// 	$personas->set_estado_civil($dato["estado_civil"]);
	// 	$personas->set_email($dato["email"]);
	// 	$personas->set_grado_academico($dato["grado_academico"]);
	// 	$usuarios->set_cedula_persona($dato["cedula_persona"]);
	// 	$usuarios->set_rol($dato["rol"]);
	// 	$usuarios->set_privilegios($dato["privilegios"]);
	// 	$usuarios->set_contrasenia($dato["contraseña"]);
	// 	$usuarios->set_pregunta_seg_1($dato["pregunta_seg_1"]);
	// 	$usuarios->set_respuesta_1($dato["respuesta_1"]);
	// 	$usuarios->set_pregunta_seg_2($dato["pregunta_seg_2"]);
	// 	$usuarios->set_respuesta_2($dato["respuesta_2"]);
	// 	$usuarios->set_estado($dato["estado"]);
	// }
 ?>